name: Deploy WASM Demo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EM_VERSION: 3.1.60
      EM_CACHE_FOLDER: 'emsdk-cache'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Build project with emcmake
        run: |
          mkdir -p build
          cd build
          emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          emmake ninja

      - name: Copy output to dist folder
        run: |
          mkdir dist
          cp build/*.html build/*.js build/*.wasm dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist